# Default values for minetest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
server:
  image: ghcr.io/linuxserver/minetest
  service:
    type: ClusterIP
    port: 30000
  resources:
    limits:
      cpu: 4
      memory: 8Gi
client:
  image: tillepille/minetest-client
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 4
      memory: 4Gi

image:
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

ingress:
  enabled: true
  host: ab.staging.talentplatforms.net

users:
  - user1
  - user2
  - user3
  - user4
  - user5
  - user6
  - user7
  - user8
  - user9
  - user10
