{{- if .Values.ingress.enabled -}}
{{- $fullName := include "minetest.fullname" . -}}
{{- $svcPort := .Values.client.service.port -}}
{{- $root := . -}}
{{- $host := .Values.ingress.host -}}
{{- range .Values.users }}
{{- if semverCompare ">=1.14-0" $root.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-client-{{ . }}
  labels:
    {{- include "minetest.labels" $root | nindent 4 }}
spec:
   rules:
    - host: {{ printf "%s-minetest.%s" . $host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-client-{{ . }}
              servicePort: {{ $svcPort }}
---
{{- end -}}
{{- end -}}
