{{ $root := . }}
{{- range .Values.users }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minetest.fullname" $root }}-client-{{ . }}
  labels:
    {{- include "minetest.labels" $root | nindent 4 }}
spec:
  type: {{ $root.Values.client.service.type }}
  ports:
    - port: {{ $root.Values.client.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "minetest.selectorClientLabels" $root | nindent 4 -}}{{ . }}
---
{{- end -}}
