apiVersion: v1
kind: Service
metadata:
  name: {{ include "minetest.fullname" . }}
  labels:
    {{- include "minetest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "minetest.selectorLabels" . | nindent 4 }}
